# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e3ff7df37e15456d2387b6638bdcd39a9827cc95bac46a9379f55d393f7b0e9874d8aa085838f0e966aafe08df1bab38ce904a10c71eec3b8b24621422fbab5

test:
  secret_key_base: 0213508f67fdcd2cdd1b58ad0cab84e99810f1082ae9392b4c718ef30fbe0e4396eab80583f05df6c22c8b438953212c7f2d2a90a00b70a523623d19a44d8650

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
